<?php

$users_users = [
			["id" => "1",
			 "status" => "success",
			 "user_name" => "Oliver Kopyov",
			 "data-filter-tags" => "oliver kopyov",
			 "style_link"  => "img/demo/avatars/avatar-b.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "IT Director, Gotbootstrap Inc.",
			 "user_phone" => "+1 317-456-25-64",
			 "email"   => "oliver.kopyov@smartadminwebapp.com",
			 "adress" => " 15 Charist St, Detroit, MI, 48212, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			["id" => "2",
			 "status" => "warning",
			 "user_name" => "Alita Gray",
			 "data-filter-tags" => "alita gray",
			 "style_link"  => "img/demo/avatars/avatar-c.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Project Manager, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-461-13-47",
			 "email"   => "Alita@smartadminwebapp.com",
			 "adress" => " 134 Hamtrammac, Detroit, MI, 48314, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "3",
			 "status" => "danger",
			 "user_name" => "Dr. John Cook PhD",
			 "data-filter-tags" => "dr john cook", 
			 "style_link"  => "img/demo/avatars/avatar-e.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Human Resources, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-13-47",
			 "email"   => "john.cook@smartadminwebapp.com",
			 "adress" => " 55 Smyth Rd, Detroit, MI, 48341, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "4",
			 "status" => "success",
			 "user_name" => "Jim Ketty",
			 "data-filter-tags" => "jim ketty",
			 "style_link"  => "img/demo/avatars/avatar-k.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Staff Orgnizer, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-33-14",
			 "email"   => "jim.ketty@smartadminwebapp.com",
			 "adress" => " 134 Tasy Rd, Detroit, MI, 48212, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "5",
			 "status" => "success",
			 "user_name" => "Dr. John Oliver",
			 "data-filter-tags" => "aaron tellus",
			 "style_link"  => "img/demo/avatars/avatar-g.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Oncologist, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-81-34",
			 "email"   => "john.oliver@smartadminwebapp.com",
			 "adress" => " 134 Gallery St, Detroit, MI, 46214, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "6",
			 "status" => "success",
			 "user_name" => "Sarah McBrook",
			 "data-filter-tags" => "sarah mcbrook",
			 "style_link"  => "img/demo/avatars/avatar-h.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Xray Division, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-76-13",
			 "email"   => "sarah.mcbrook@smartadminwebapp.com",
			 "adress" => " 13 Jamie Rd, Detroit, MI, 48313, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "7",
			 "status" => "success",
			 "user_name" => "Jimmy Fellan",
			 "data-filter-tags" => "jimmy fellan",
			 "style_link"  => "img/demo/avatars/avatar-i.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Accounting, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-43-14",
			 "email"   => "jimmy.fallan@smartadminwebapp.com",
			 "adress" => " 55 Smyth Rd, Detroit, MI, 48341, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
			 ["id" => "8",
			 "status" => "success",
			 "user_name" => "Arica Grace",
			 "data-filter-tags" => "arica grace",
			 "style_link"  => "img/demo/avatars/avatar-j.png",
			 "user_link" => "javascript:void(0);",
			 "user_position" => "Accounting, Gotbootstrap Inc.",
			 "user_phone"=> "+1 313-779-33-47",
			 "email"   => "arica.grace@smartadminwebapp.com",
			 "adress" => " 798 Smyth Rd, Detroit, MI, 48341, USA",
			 "vk_link" => "https://www.vk.com",
			 "telegram_link" => "https://www.telegram.com",
			 "instagram_link" => "https://www.instagram.com"
			 ],
	    ];



?>